server:
  port: 8301

info:
  app:
    name: Action Processor
    version: 1.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximumPoolSize: 50

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: actionv2
        jdbc:
          lob:
            non_contextual_creation: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  inbound-queue: case.action
  action-fulfilment-inbound-queue: action.fulfilment
  events-exchange: events
  outbound-printer-queue: Action.Printer
  outbound-field-queue: Action.Field
  outbound-exchange: action-outbound-exchange
  action-case-exchange: action-case-exchange
  undelivered-mail-queue: action.undeliveredMailQueue
  consumers: 50
  retry-attempts: 3
  retry-delay: 1000 #milliseconds
  quarantine-exchange: quarantineExchange

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/action-scheduler-healthy

scheduler:
  frequency: 1000 #milliseconds
  chunksize: 1000

caseapi:
  host: caseapi
  port: 8161

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false

logging:
  level:
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR