package uk.gov.ons.census.action.model.dto;

public enum EventType {
  CASE_CREATED,
  CASE_UPDATED,
  UAC_UPDATED,
  PRINT_CASE_SELECTED,
  FULFILMENT_REQUESTED,
  FIELD_CASE_SELECTED,
  UNDELIVERED_MAIL_REPORTED
}
